AppViajes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from AppViajes.views import *
from AppAccounts.views import *
   

app_name = 'AppViajes' 

urlpatterns = [
    path('',inicio ,name="Inicio"),
    path('pages/',pages ,name="Pages"),
    path('about/',about,name="About"),
    path('mensajes/',detallemensajes.as_view() ,name="Mensajes"),
    path('<str:slug>/', detallepost,name="Detalle_post"),
    path('account/login/', login_request,name="Login"),
    path('account/logout/', LogoutView.as_view(template_name='AppAccounts/logout.html'),name="Logout"),
    path('listar_post',ListarPost.as_view(), name='listar_post'),
    path('crear_post',CrearPost.as_view(),name="Crear_post"),
    path('editar_post/<int:pk>',EditarPost.as_view(),name="Editar_post"),
    path('eliminar_post/<int:pk>',EliminarPost.as_view(),name="Eliminar_post"),
    path('account/signup/', register,name="Register"),
    path('account/profile/', profile,name="profile"),
    path('account/profile_view/',profile_view,name="profile_view"),
]

ProyectoBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.shortcuts import redirect
from AppViajes.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls, name='Admin'),
    path('AppViajes/', include('AppViajes.urls')),
    path('', lambda req: redirect('AppViajes:Inicio')),  
]

#para las imágenes
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve , {
            'document_root':settings.MEDIA_ROOT,
        }),
    ]

AppAccounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from AppViajes.models import Post
from django.contrib.auth.decorators import login_required

# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    nombre=models.CharField(max_length=120, null=True, blank=True)
    apellido=models.CharField(max_length=120, null=True, blank=True)
    email=models.EmailField()
    foto=models.ImageField(upload_to='profiles', null=True, blank=True)
    descripcion=models.CharField(max_length=350, null=True, blank=True)
    web=models.URLField(max_length=200, null=True, blank=True)
    
    def __str__(self):
        return self.user.username
      

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

AppAccounts/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from ckeditor.fields import RichTextField

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class meta:
        model = User
        fields = ('username','email')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        model = Profile
        fields = ('web','descripcion')

class UserProfileForm(UserCreationForm):
    first_name=forms.CharField(max_length=120)
    last_name=forms.CharField(max_length=120)
    email=forms.EmailField()
    web=forms.URLField(max_length=200)
    descripcion=forms.CharField(max_length=350)
#    foto=forms.ImageField()

AppAccounts/views.py
from django.shortcuts import render, redirect
import django

#para el log in, log out y register
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from .forms import UserRegisterForm, UserForm, UserProfileForm
from django.contrib.auth.models import User
from django.views.generic import ListView

#para el profile
from .models import Profile


def login_request (request):

    if request.method=='POST':
        #validar el usuario
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            usuario = form.data.get ('username')
            passwd = form.data.get ('password')

            user = authenticate(username=usuario, password=passwd)

            if user:
                login(request,user)
                
                return redirect('AppViajes:Inicio')
           
            else:
                return redirect('AppViajes:Login')

        else:
            return redirect('AppViajes:Login')
        
    form = AuthenticationForm()

    return render(request,'AppAccounts/login.html', {'form': form})

def register(request):
    if request.method=='POST':

        form=UserRegisterForm(request.POST)

        if form.is_valid():

            username=form.data['username']
            try:
                user_new=User.objects.get(username=username)
            except django.contrib.auth.models.User.DoesNotExist:
                user_new=None

            if not user_new:
                
                form.save()

            return redirect('AppViajes:Login')
    
    else:
        form=UserRegisterForm(request.POST)

    return render(request, 'AppAccounts/register.html', {'form': form})

def profile (request):

    usuario=request.user

    if request.method == 'POST':
        
        user_form = UserProfileForm(request.POST, instance=request.user)
        	    
        if user_form.is_valid():
            informacion = user_form.data
            usuario.email = informacion['email']
            usuario.password1 = informacion['password1']
            usuario.password2 = informacion['password2']        
            usuario.last_name = informacion['last_name']      
            usuario.first_name = informacion['first_name'] 
            usuario.save()
            
            if Profile.objects.filter(user=usuario):
                profile = Profile.objects.get(user=usuario)
            #    profile.foto = informacion['foto']
                profile.descripcion = informacion['descripcion']
                profile.web = informacion['web']
            else:
                profile=Profile(
                    user=usuario,
            #        foto=informacion['foto'],
                    descripcion=informacion['descripcion'],
                    web=informacion['web']
                    )

            profile.save()

            return redirect ('AppViajes:profile_view')
    else:
        user_form = UserProfileForm(initial={'username':usuario.username, 'email':usuario.email,'first_name':usuario.first_name,'last_name':usuario.last_name})

    return render(request, 'AppAccounts/profile_form.html', {"user":request.user, "user_form":user_form})

def profile_view (request):

    usuario=request.user

    if request.method == 'POST':
        
        user_form = UserProfileForm(request.POST, instance=request.user)
        	    
        if user_form.is_valid():
            informacion = user_form.data
            usuario.email = informacion['email']
            usuario.password1 = informacion['password1']
            usuario.password2 = informacion['password2']        
            usuario.last_name = informacion['last_name']      
            usuario.first_name = informacion['first_name'] 
            
            profile = Profile.objects.get(user=usuario)
        #    profile.foto = informacion['foto']
            profile.descripcion = informacion['descripcion']
            profile.web = informacion['web']

    else:
        user_form = UserProfileForm(initial={'username':usuario.username, 'email':usuario.email,'first_name':usuario.first_name,'last_name':usuario.last_name})

    return render(request, 'AppAccounts/profile.html', {"user":request.user, "user_form":user_form})

templates/AppAccounts/login.html
<!DOCTYPE html>

{% extends 'AppViajes/index.html'%}
{% load static %}

{% block titulo_principal%}
Ingresá!
<span class="subheading" style="color:#FFFFF0"><strong>Y podrás distfrutar al maximo de este Blog </strong></span>
{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/login.webp'%}

{% endblock imagen %}

{%block contenido%}

<h3 span class="subheading">Ingresa tu usuario y contraseña</h3>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
<head>

<body>
    <form method="post">{%csrf_token%}
      <FONT FACE="Franklin Gothic Medium">
        {{form.as_p}}
      </FONT>
      <div style='text-align:center'><input type="submit" value="Login"></div>

    </form>
  </body>
</html>

{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}

templates/AppAccounts/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Logout</title>
</head>

<body>
    {% extends 'AppViajes/index.html'%}
    {% load static %}
    
    {% block titulo_principal%}
    <h2>Gracias por visitar nuestro sitio. ¡Hasta pronto!</h2>
    
    {% endblock titulo_principal %}
    
    {% block imagen %}
    
    {% static 'AppViajes/assets/img/logout.jpg'%}
    
    {% endblock imagen %}
    
    {%block contenido%}
    
    <h5><center> <FONT FACE="Ink free">Cortos, largos, planeados, sin rumbos, lo importante es VIAJAR!</FONT></center></h5>
    {%endblock contenido%}
    
    {%block busqueda%}
    {%endblock busqueda%}
</body>
</html>

templates/AppAccounts/profile.html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile</title>
<head>

{% extends 'AppViajes/index.html'%}
{% load static %}
  
{% block titulo_principal%}
Perfil de usuario
<span class="subheading" style="color:#FFFFF0"><strong>Aquí podrás ver los datos cargados en tu perfil y acceder a su edición</strong></span>
{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/register.webp'%}

{% endblock imagen %}

{%block contenido%}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{user_form.as_table}}
  <table>
      <button style="margin: 10px" type="button" class="btn btn-secondary"><a class="nav-link px-lg-3 py-3 py-lg-1" href="{% url 'AppViajes:profile' %}"><FONT SIZE=3 COLOR="white">Editar perfil</FONT></a></button>
      <button style="margin: 10px" type="button" class="btn btn-secondary"><a class="nav-link px-lg-3 py-3 py-lg-1" href="{% url 'AppViajes:Inicio' %}"><FONT SIZE=3 COLOR="white">Cerrar</FONT></a></button>
<form>

{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}
  

templates/AppAccounts/profile_form.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Edit</title>
<head>
  
  {% extends 'AppViajes/index.html'%}
  {% load static %}
    
  {% block titulo_principal%}
  Edición de perfil
  <span class="subheading" style="color:#FFFFF0"><strong>Podés cambiar los datos de tu perfil. No olvides guardar las modificaciones.</strong></span>
  {% endblock titulo_principal %}
  
  {% block imagen %}
  
  {% static 'AppViajes/assets/img/register.webp'%}
  
  {% endblock imagen %}
  
    {%block contenido%}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{user_form.as_table}}
        <table>
        <button style="margin: 10px" type="submit" class="btn btn-secondary"><a class="nav-link px-lg-3 py-3 py-lg-1" href="{% url 'AppViajes:Inicio' %}"><FONT SIZE=3 COLOR="white">Guardar cambios</FONT></a></button>
        <button style="margin: 10px" type="button" class="btn btn-secondary"><a class="nav-link px-lg-3 py-3 py-lg-1" href="{% url 'AppViajes:Inicio' %}"><FONT SIZE=3 COLOR="white">Cerrar</FONT></a></button>
    
    </form>

    {%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}

templates/AppAccounts/register.html
<!DOCTYPE html>

{% extends 'AppViajes/index.html'%}
{% load static %}

{% block titulo_principal%}
Registrate!
<span class="subheading" style="color:#FFFFF0"><strong>Y forma parte de nuestra comunidad</strong></span>
{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/register.webp'%}

{% endblock imagen %}

{%block contenido%}

<h3> <span class="subheading">Completá los campos para registrarte en nuestro blog.</span></h3>
</br>
</br>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register</title>
</head>

<body>
    <form method="post">{%csrf_token%}
      <FONT FACE="Franklin Gothic Medium">
        {{form.as_p}}
      </FONT>
        <div style='text-align:left'><input type="submit" value="Enviar">

    </form>
  </body>
</html>

{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}