AppViajes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from AppViajes.views import *
from AppAccounts.views import *
   

app_name = 'AppViajes' 

urlpatterns = [
    path('',inicio ,name="Inicio"),
    path('pages/',pages ,name="Pages"),
    path('about/',about,name="About"),
    path('mensajes/',detallemensajes.as_view() ,name="Mensajes"),
    path('<str:slug>/', detallepost,name="Detalle_post"),
    path('account/login/', login_request,name="Login"),
    path('account/logout/', LogoutView.as_view(template_name='AppAccounts/logout.html'),name="Logout"),
    path('listar_post',ListarPost.as_view(), name='listar_post'),
    path('crear_post',CrearPost.as_view(),name="Crear_post"),
    path('editar_post/<int:pk>',EditarPost.as_view(),name="Editar_post"),
    path('eliminar_post/<int:pk>',EliminarPost.as_view(),name="Eliminar_post"),
    path('account/signup/', register,name="Register"),
    path('account/profile/', profile,name="profile"),
    path('account/profile_view/',profile_view,name="profile_view"),
]

ProyectoBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.shortcuts import redirect
from AppViajes.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls, name='Admin'),
    path('AppViajes/', include('AppViajes.urls')),
    path('', lambda req: redirect('AppViajes:Inicio')),  
]

#para las imágenes
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve , {
            'document_root':settings.MEDIA_ROOT,
        }),
    ]

AppViajes/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

class Post(models.Model):
    id=models.AutoField(primary_key= True)
    titulo=models.CharField('Titulo',max_length=50,null= False, blank= False)
    subtitulo=models.CharField('Subtitulo',max_length=30)
    slug=models.CharField('Slug',max_length=100,null= False, blank= False)
    contenido=RichTextField()
    #imagen=models.ImageField('Imagen Referencial', upload_to= 'imagenes_post/', null= True, blank= True)
    #imagen=models.URLField(max_length=300, null= False, blank= False)
    autor=models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion=models.DateField('Fecha de creación', auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.titulo

class Mensaje(models.Model):
    id=models.AutoField(primary_key= True)
    autor_mensaje=models.ForeignKey(User, on_delete=models.CASCADE)
    mensaje=RichTextField()
    dirigido_a=models.ForeignKey(Post, on_delete=models.CASCADE)
    fecha_creacion_mensaje=models.DateField('Fecha de creación', auto_now=False, auto_now_add=True)
    

    def __str__(self):
        return self.mensaje

AppViajes/forms.py
from django import forms
from AppViajes.models import Mensaje

from AppViajes.models import Post


class MensajeFormulario(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = ['mensaje']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo', 'subtitulo', 'slug', 'contenido', 'autor']

AppViajes/views.py
from django.shortcuts import  render

from .models import Post, Mensaje
from AppViajes.forms import MensajeFormulario, PostForm
from django.db.models import Q
from django.views.generic import ListView
from django.views.generic.edit import CreateView,DeleteView, UpdateView

# Create your views here.

def inicio(request):
    return render (request, 'AppViajes/inicio.html')


def pages(request):
    busqueda=request.GET.get("buscar")
    posts =Post.objects.filter().order_by('-fecha_creacion')
    
    #para la barra de busqueda:

    if busqueda:
        posts = Post.objects.filter(
            Q(titulo__icontains = busqueda) |
            Q(contenido__icontains = busqueda) |
            Q(subtitulo__icontains = busqueda)
             ).distinct()
       
    return render(request, 'AppViajes/index.html', {'posts':posts})


def detallepost(request, slug):
    post =Post.objects.get(
        slug = slug
    )
    
    mensajes=Mensaje.objects.filter(dirigido_a=post.id).order_by('-fecha_creacion_mensaje')
   
    #para enviar mensaje a traves de formulario:
    
    if request.method == 'POST':
        miFormulario = MensajeFormulario(request.POST)
        print(miFormulario)
        
        if miFormulario.is_valid:
            usuario= request.user
            mensaje =miFormulario.cleaned_data.get("mensaje")
            mensaje= Mensaje.objects.create(autor_mensaje=usuario,mensaje=mensaje,dirigido_a=post)
    miFormulario = MensajeFormulario()

    return render(request, 'AppViajes/post.html', {'Detalle_post':post,'mensajes':mensajes, 'miFormulario': miFormulario})

class detallemensajes(ListView):
    model = Mensaje
    template_name = 'AppViajes/mensajes.html'

    def get(self, request, *args, **kwargs):
        self.queryset = Mensaje.objects.filter(dirigido_a__autor=request.user).order_by('-fecha_creacion_mensaje')
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        return self.render_to_response(context)


# CRUD de posts:

class ListarPost(ListView):
    model = Post
    template_name = 'AppViajes/listar_post.html'

    def get_queryset(self):
        return Post.objects.filter(autor=self.request.user).order_by('-fecha_creacion')


class CrearPost(CreateView):
    model = Post
    form_class = PostForm
    success_url = '/AppViajes/listar_post'


class EditarPost(UpdateView):
    model = Post
    template_name = 'AppViajes/post_form.html'
    form_class = PostForm
    success_url = '/AppViajes/listar_post'


class EliminarPost(DeleteView):
    model = Post
    success_url = '/AppViajes/listar_post'


# Vista about:
def about(request):
    return render (request, 'AppViajes/about.html')

templates/AppViajes/about.html
{% extends 'AppViajes/index.html'%}
{% load static %}

{% block titulo_principal%}
Sobre nosotros
<span class="subheading" style="color:#EEE8AA"><strong>Somos un grupo de amigos apasionados por conocer nuevos lugares y acumular nuevas experiencias. En este blog buscamos compartir nuestras aventuras y brindar el espacio para que también otros viajeros puedan hacerlo. Conozcamos juntos el mundo entero. </strong></span>

{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/about-bg.jpg'%}

{% endblock imagen %}

{%block contenido%}


{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}

templates/AppViajes/contact.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/AppViajes/crear_post.html
{% extends 'AppViajes/index.html'%}
{% load static %}

{%block busqueda%}
{%endblock busqueda%}


{% block titulo_principal%}

Contá tu experiencia!

{% endblock titulo_principal %}

{% block imagen%}
{% static 'AppViajes/assets/img/Cuaderno-de-viaje-scaled.jpg'%}

{% endblock imagen %}


{%block contenido%}
<p>
  <form method="POST"> 
    {% csrf_token %} 
    {{ form.media }}
      {{ form.as_p }} 
      <input type="submit" class="btn btn-primary text-uppercase" value="Guardar Post">
      
    </form>

</p>

{%endblock contenido%}

templates/AppViajes/index.html
{% load static %}
<!DOCTYPE html>

<!-- template Padre-->

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block titulo%} Viajeros {% endblock titulo%} </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'AppViajes/css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>

        <!-- Navigation-->
      <!-- Si el usuario SI está logeado mostrar el nombre de usuario -->
      {% if request.user.is_authenticated %}
        <nav class="navbar-brand" id="mainNav">
            <FONT FACE="Ink free"><class="nav-item mx-0 mx-lg-1"><a class="nav-link px-lg-3 py-3 py-lg-4" style="color:#FFFAF0" >Bienvenido {{user.username}} </a></FONT>
        {% endif %}

        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Inicio' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Pages' %}">Blog</a></li>
                        

                        <!-- Si el usuario está logueado, mostrar el nombre de usuario y los botones Tus Posteos, Mensajes, Profile y Logout-->
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:listar_post' %}">Tus Posteos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Mensajes' %}">Mensajes</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:profile_view' %}">Profile</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Logout' %}">Log out</a></li>
                        {% endif %} 

                        <!-- Si el usuario no está logueado, mostrar los botones Register y Login-->
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Register' %}">Register</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:Login' %}">Login</a></li>
                        {% endif %}                       
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'AppViajes:About' %}">About us</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </nav>

        <!-- Page Header-->
       
        <header class="masthead" style="background-image: url({% block imagen %}{% static 'AppViajes/assets/img/fondo.jpg'%}{% endblock imagen %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{% block titulo_principal%} Nuestro blog</h1>
                            <span class="subheading">Recorre nuestros post y sorprendete</span>
                            {% endblock titulo_principal%}
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <!-- boton busqueda post-->

            {%block busqueda%}
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 search">
                            <form method="get">
                                <div id="custom-search-input">
                                    <div class="input-group col-md-12">
                                        <input type="text" class="form-control" placeholder="Buscar..." name="buscar" value = "{{ request.GET.buscar }}">
                                        <span class="input-group-list">
                                            <i class="icon icon-search"></i>
                                            <button type="submit"  class="btn btn-primary text-uppercase">Buscar</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
        {%endblock busqueda%}
        </header>

        <!-- Main Content-->
        
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                        {%block contenido%}
                            <hr class="my-4" />
                            {% if posts %}
                                {% for post in posts %}
                                    <div class="post-preview">
                                    <a href= "{% url 'AppViajes:Detalle_post' post.slug %}">
                                        <h2 class="post-title">
                                            {{post.titulo}}
                                        </h2>
                                        <h5 style="color:#808000" class="post-subtitulo">
                                            {{post.subtitulo}}
                                        </h5>
                                    </a>
                                    <p class="post-meta">
                                        Escrito por
                                        <a href="#!">{{post.autor}}</a> el
                                        {{post.fecha_creacion |date:"d-m-y"}}
                                    </p>
                                    </div>
                                    <hr class="my-4" />
                                {% endfor %}
                                {% else%}
                                    <h2><center>No existen post registrados con esa descripción</center></h2>
                            {% endif%}

                        {%endblock contenido%}

                </div>
            </div>
        </div>
        </br>
        </br>
     </body>

templates/AppViajes/inicio.html
{% extends 'AppViajes/index.html'%}
{% load static %}

<!-- Inicio blog-->

{% block titulo_principal%}
Viajeros
<span class="subheading" style="color:#EEE8AA"><strong>Es una comunidad de viajeros que visitan cada rincón de nuestro país y comparten mucha informacion de lugares, eventos, actividades, alojamientos, gastronomía.</strong></span>

{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/inicio.jpg'%}

{% endblock imagen %}

{%block contenido%}
{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}

templates/AppViajes/listar_post.html
{% extends 'AppViajes/index.html'%}
{% load static %}


{% block titulo_principal%}

Tu Blog

<span class="subheading">Creá, editá y eliminá tus posteos:</span>

{% endblock titulo_principal %}

{%block busqueda%}
{%endblock busqueda%}

{% block imagen%}
{% static 'AppViajes/assets/img/fondo.jpg'%}

{% endblock imagen %}


{%block contenido%}
<h1></h1>
{% if object_list %}
    {% for post in object_list %}
                                <div class="post-preview">
                                    <a href= "{% url 'AppViajes:Detalle_post' post.slug %}">
                                        <h2 class="post-title">
                                            {{post.titulo}}
                                        </h2>
                                        <h5 style="color:#808000" class="post-subtitulo">
                                            {{post.subtitulo}}
                                        </h5>
                                    
                                    </a>
                                    <div>
                                    <div> <a class="btn btn-danger btn-sm" style= "float: right;" href="{% url 'AppViajes:Eliminar_post' post.id%}">Eliminar</a></div>    
                                    <div> <a class="btn btn-primary btn-sm"  style= "float: right;"  href="{% url 'AppViajes:Editar_post' post.id%}">Editar </a></div>
                                    
                                    </div>
                                    <p class="post-meta">
                                        Escrito por
                                        <a href="#!">{{post.autor}}</a> el
                                        {{post.fecha_creacion |date:"d-m-y"}}
                                       
                                    </p>
                                
                                </div>
                                <hr>
                                
                            {% endfor %}    

                            
                            {% else %}
                             <h3>No hay posteos registrados.</h3>
                             {% endif %}
                            


</ul>
<p>


    <!-- boton crear post-->

    <p>
    

    <div align="center"><a class="btn btn-primary text-uppercase"  href="{% url 'AppViajes:Crear_post' %}">Crear Post →</a></div>

   
    </p>

{%endblock contenido%}

templates/AppViajes/mensajes.html
{% extends 'AppViajes/index.html'%}
{% load static %}

<!-- lista de mensajes del usuario logeado-->

{% block titulo_principal%}

Mensajes

{% endblock titulo_principal %}

{% block imagen %}

{% static 'AppViajes/assets/img/mensajes.webp'%}

{% endblock imagen %}

{%block contenido%}

{% if object_list %}
<h5 style="color:#808000">Estos son los mensajes que los usuarios hicieron a tus posts:</h5>

    {% for mensaje in object_list %}
    <hr class="my-4" />
    <h5>Post: {{mensaje.dirigido_a}}</h5>
    {{mensaje.mensaje |safe}}
    <FONT FACE="Ink free">Enviado por {{mensaje.autor_mensaje}} el {{mensaje.fecha_creacion_mensaje|date:"d-m-y"}}</FONT>
    {% endfor %}
{% else %}
    <h3>No hay mensajes registrados en sus posts.</h3>
{% endif %}

{%endblock contenido%}

{%block busqueda%}
{%endblock busqueda%}

templates/AppViajes/post.html
{% extends 'AppViajes/index.html'%}
{% load static %}

<!-- lista de post-->

{% block titulo%}

{{Detalle_post.titulo}}

{% endblock titulo %}

{% block titulo_principal%}

<h1>{{ Detalle_post.titulo }}</h1>
<h4>{{ Detalle_post.subtitulo }}</h4>

{% endblock titulo_principal %}


{% block imagen%}

{% static 'AppViajes/assets/img/como-empezar-un-blog-de-viajes-1024x512.png'%}

{% endblock imagen %}

{%block contenido%}

{%block busqueda%}

{%endblock busqueda%}

<!-- para mostrar quien escribio el post-->
{{Detalle_post.contenido | safe}}
<FONT FACE="Segoe Print" style="color:#696969"><div style='text-align:right'> Escrito por {{Detalle_post.autor}} ({{Detalle_post.fecha_creacion | date:"m-y"}}) </div></FONT>

<!-- para mostrar los mensajes del post-->
</br>
</br>
<h5 style="color:#808000">Mensajes:</h5>

{% if mensajes %}

  {% for mensaje in mensajes %}
        {{mensaje|safe}}
        </br>
        <FONT FACE="Ink free">Enviado por {{mensaje.autor_mensaje}} el {{mensaje.fecha_creacion_mensaje |date:"d-m-y"}}</FONT>
        <hr class="my-4" />
  {% endfor %}

{% else %}
    <h6><p>No hay mensajes registrados.</p></h6>
{% endif %}

<!-- para dejar mensajes al post-->

{% if request.user.is_authenticated %}

<h5 style="color:#808000">Deja tus comentarios aqui:</h5>

<form action="{{request.path}}" method="POST" > {% csrf_token%}

  {{miFormulario.as_p}}
  {{miFormulario.media}}

  <input type="submit" class="btn btn-primary text-uppercase" value="Enviar">
</form>
{% endif %}

{%endblock contenido%}

templates/AppViajes/post_confirm_delete.html
{% extends 'AppViajes/index.html'%}
{% load static %}


{%block busqueda%}
{%endblock busqueda%}


{% block titulo_principal%}



{% endblock titulo_principal %}

{% block imagen%}
{% static 'AppViajes/assets/img/Cuaderno-de-viaje-scaled.jpg'%}

{% endblock imagen %}


{%block contenido%}
<link rel="shortcut icon" href="#">
<p>
  <form method="POST"> 
    {% csrf_token %} 
    <p> <strong>¿Estás seguro que deseas eliminar el post: {{object.titulo}}? </strong></p>
    <button type="sumbit" class="btn btn-danger">Confirmar</button>
   
    </form>
     
</p>
<a class="btn btn-primary "   href="{% url 'AppViajes:listar_post'%}">Cancelar </a>

<p>
</p>  
{%endblock contenido%}

templates/AppViajes/post_form.html
{% extends 'AppViajes/index.html'%}
{% load static %}

{%block busqueda%}
{%endblock busqueda%}


{% block titulo_principal%}

Contá tu experiencia!

{% endblock titulo_principal %}

{% block imagen%}
{% static 'AppViajes/assets/img/Cuaderno-de-viaje-scaled.jpg'%}

{% endblock imagen %}


{%block contenido%}
<p>
  <form method="POST"> 
    {% csrf_token %} 
    {{ form.media }}
      {{ form.as_p }} 
      <input type="submit" class="btn btn-primary text-uppercase" value="Guardar Post">
     
    </form>

</p>
<a class="btn btn-primary "   href="{% url 'AppViajes:listar_post'%}">CANCELAR </a>
<p>
</p>
{%endblock contenido%}